// <auto-generated />
namespace najdiPrevoz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class new1111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new1111));
        
        string IMigrationMetadata.Id
        {
            get { return "202009111719166_new1111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
