// <auto-generated />
namespace najdiPrevoz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class promena1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(promena1));
        
        string IMigrationMetadata.Id
        {
            get { return "202009212033156_promena1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
